services:
  db_prod:
    restart: always
    container_name: db-prod
    image: postgres:13
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432

  web_prod:
    restart: always
    container_name: web-prod
    build: .
    volumes:
      - .:/code
    depends_on:
      - db_prod
    links:
      - db_prod:db_prod